# Generated by Django 5.1 on 2024-09-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('ban_user', 'can ban a user')]},
        ),
    ]
