# Generated by Django 5.1 on 2024-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default/image.png', upload_to='images/'),
        ),
    ]
