# Generated by Django 5.1 on 2024-09-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0004_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
