# Generated by Django 5.1 on 2024-09-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0005_profile_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='text',
        ),
    ]
