# Generated by Django 5.1 on 2024-09-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0006_remove_profile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default/image.png', upload_to='profile_pics/'),
        ),
    ]
